### ISSUE TITLE
Save without a tag specified causes weird error message

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/files_automatedtagging#11]
While testing #10 I tried to save a rule without specify a tag and got following:

<img width="1086" alt="bildschirmfoto 2016-08-19 um 14 51 26" src="https://cloud.githubusercontent.com/assets/245432/17810308/a1c7a41e-661c-11e6-936d-b8068c71ed2a.png">

Part of the essential output:

```
<h2><strong>Technische Details</strong></h2> <ul> <li>Entfernte Adresse: ::1</li> <li>Anfragekennung: K2cbjCKQyXwB2Bztl7Hs</li> <li>Typ: InvalidArgumentException</li> <li>Code: 0</li> <li>Nachricht: Tag id must be integer</li> <li>Datei: /Users/morrisjobke/Projects/nextcloud/server/lib/private/SystemTag/SystemTagManager.php</li> <li>Zeile: 99</li> </ul> <br /> <h2><strong>Ablauf</strong></h2> <pre>#0 /Users/morrisjobke/Projects/nextcloud/server/apps/files_automatedtagging/lib/Operation.php(83): OC\SystemTag\SystemTagManager-&gt;getTagsByIds(Array) #1 /Users/morrisjobke/Projects/nextcloud/server/apps/workflowengine/lib/Manager.php(260): OCA\FilesAutomatedTagging\Operation-&gt;validateOperation(&#039;ewrwer&#039;, Array, &#039;&#039;) #2 /Users/morrisjobke/Projects/nextcloud/server/apps/workflowengine/lib/Manager.php(180): OCA\WorkflowEngine\Manager-&gt;validateOperation(&#039;OCA\\FilesAutoma...&#039;, &#039;ewrwer&#039;, Array, &#039;&#039;) #3 /Users/morrisjobke/Projects/nextcloud/server/apps/workflowengine/lib/Controller/FlowOperations.php(69): OCA\WorkflowEngine\Manager-&gt;addOperation(&#039;OCA\\FilesAutoma...&#039;, &#039;ewrwer&#039;, Array, &#039;&#039;) #4 [internal function]: OCA\WorkflowEngine\Controller\FlowOperations-&gt;addOperation(&#039;OCA\\FilesAutoma...&#039;, &#039;ewrwer&#039;, Array, &#039;&#039;) #5 /Users/morrisjobke/Projects/nextcloud/server/lib/private/AppFramework/Http/Dispatcher.php(160): call_user_func_array(Array, Array) #6 /Users/morrisjobke/Projects/nextcloud/server/lib/private/AppFramework/Http/Dispatcher.php(90): OC\AppFramework\Http\Dispatcher-&gt;executeController(Object(OCA\WorkflowEngine\Controller\FlowOperations), &#039;addOperation&#039;) #7 /Users/morrisjobke/Projects/nextcloud/server/lib/private/AppFramework/App.php(117): OC\AppFramework\Http\Dispatcher-&gt;dispatch(Object(OCA\WorkflowEngine\Controller\FlowOperations), &#039;addOperation&#039;) #8 /Users/morrisjobke/Projects/nextcloud/server/lib/private/AppFramework/Routing/RouteActionHandler.php(47): OC\AppFramework\App::main(&#039;FlowOperationsC...&#039;, &#039;addOperation&#039;, Object(OC\AppFramework\DependencyInjection\DIContainer), Array) #9 [internal function]: OC\AppFramework\Routing\RouteActionHandler-&gt;__invoke(Array) #10 /Users/morrisjobke/Projects/nextcloud/server/lib/private/Route/Router.php(298): call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array) #11 /Users/morrisjobke/Projects/nextcloud/server/lib/base.php(969): OC\Route\Router-&gt;match(&#039;/apps/workflowe...&#039;) #12 /Users/morrisjobke/Projects/nextcloud/server/index.php(48): OC::handleRequest() #13 {main}</pre> </span> <div class="push"></div><!-- for sticky footer --> </div> </div> <footer role="contentinfo"> <p class="info"> <a href="https://nextcloud.com" target="_blank" rel="noreferrer">Nextcloud</a> – ein sicherer Ort für all Ihre Daten	</p> </footer> </body> </html>
```

@nickvergessen Could you check that?

**Comment by nickvergessen** [comment]
Yeah, but that is due to #10

**Comment by MorrisJobke** [comment]
> Yeah, but that is due to #10

Isn't it a different error message? It says InvalidArgument but #10 has an UnexpectedValue excpetion.

**Comment by nickvergessen** [comment]
But it is introduced by that

**Comment by MorrisJobke** [comment]
> But it is introduced by that

Okay ... whatever you know how to fix it :)
