### ISSUE TITLE
PHP warning leads to occ breakeage

### ISSUE THREAD

**Issue by tcitworld** [nextcloud/files_automatedtagging#157]
Fixed by disabling "Files automated tagging" app.

```
Exception during scan: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?
#0 /var/www/nextcloud/lib/composer/composer/ClassLoader.php(444): OCA\Files\Command\Scan->exceptionErrorHandler(2, '"continue" targ...', '/var/www/nextcl...', 55, Array)
#1 /var/www/nextcloud/lib/composer/composer/ClassLoader.php(444): include()
#2 /var/www/nextcloud/lib/composer/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/var/www/nextcl...')
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass('OCA\\WorkflowEng...')
#4 /var/www/nextcloud/apps/workflowengine/lib/Service/RuleMatcher.php(124): spl_autoload_call('OCA\\WorkflowEng...')
#5 /var/www/nextcloud/apps/workflowengine/lib/Service/RuleMatcher.php(114): OCA\WorkflowEngine\Service\RuleMatcher->getMatchingOperations('OCA\\FilesAutoma...', false)
#6 /var/www/nextcloud/apps/files_automatedtagging/lib/Operation.php(85): OCA\WorkflowEngine\Service\RuleMatcher->getFlows(false)
#7 /var/www/nextcloud/apps/files_automatedtagging/lib/CacheListener.php(45): OCA\FilesAutomatedTagging\Operation->checkOperations(Object(OCA\Files_Trashbin\Storage), 2086198, 'files/Vid\xC3\xA9os/S...')
#8 /var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php(247): OCA\FilesAutomatedTagging\CacheListener->onCacheEvent(Object(OCP\Files\Cache\CacheUpdateEvent), 'OCP\\Files\\Cache...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#9 /var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\Component\EventDispatcher\EventDispatcher->callListeners(Array, 'OCP\\Files\\Cache...', Object(OCP\Files\Cache\CacheUpdateEvent))
#10 /var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php(80): Symfony\Component\EventDispatcher\EventDispatcher->dispatch(Object(OCP\Files\Cache\CacheUpdateEvent), 'OCP\\Files\\Cache...')
#11 /var/www/nextcloud/lib/private/EventDispatcher/SymfonyAdapter.php(63): OC\EventDispatcher\EventDispatcher->dispatch('OCP\\Files\\Cache...', Object(OCP\Files\Cache\CacheUpdateEvent))
#12 /var/www/nextcloud/lib/private/Files/Cache/Cache.php(393): OC\EventDispatcher\SymfonyAdapter->dispatch('OCP\\Files\\Cache...', Object(OCP\Files\Cache\CacheUpdateEvent))
#13 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(418): OC\Files\Cache\Cache->update(2086198, Array)
#14 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(410): OC\Files\Cache\Scanner->scanChildren('files/Vid\xC3\xA9os/S...', true, 3, 2086198, true)
#15 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(410): OC\Files\Cache\Scanner->scanChildren('files/Vid\xC3\xA9os/S...', true, 3, 2084115, true)
#16 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(410): OC\Files\Cache\Scanner->scanChildren('files/Vid\xC3\xA9os/S...', true, 3, 2084114, true)
#17 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(339): OC\Files\Cache\Scanner->scanChildren('files/Vid\xC3\xA9os/S...', true, 3, 1974942, true)
#18 /var/www/nextcloud/lib/private/Files/Utils/Scanner.php(261): OC\Files\Cache\Scanner->scan('files/Vid\xC3\xA9os/S...', true, 3)
#19 /var/www/nextcloud/apps/files/lib/Command/Scan.php(151): OC\Files\Utils\Scanner->scan('/tcit/files/Vid...', true, NULL)
#20 /var/www/nextcloud/apps/files/lib/Command/Scan.php(207): OCA\Files\Command\Scan->scanFiles('tcit', '/tcit/files/Vid...', Object(Symfony\Component\Console\Output\ConsoleOutput), false, true, false)
#21 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\Files\Command\Scan->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /var/www/nextcloud/core/Command/Base.php(168): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /var/www/nextcloud/3rdparty/symfony/console/Application.php(915): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /var/www/nextcloud/3rdparty/symfony/console/Application.php(272): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Files\Command\Scan), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /var/www/nextcloud/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /var/www/nextcloud/lib/private/Console/Application.php(214): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 /var/www/nextcloud/console.php(99): OC\Console\Application->run()
#28 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#29 {main}
```

Using Nextcloud 18.0.1, Files automated tagging 1.8.0 and php 7.3.

**Comment by tcitworld** [comment]
Probably duplicate of #19504

**Comment by FanyangMengDev** [comment]
Just met the same problem and have you solved it?

**Comment by nickvergessen** [comment]
Follow the link above and then check the last comment

**Comment by FanyangMengDev** [comment]
> Follow the link above and then check the last comment

Thank you. By changing continue to continue 2 solved this. : )

**Comment by babaz8** [comment]
> > Follow the link above and then check the last comment
> 
> Thank you. By changing continue to continue 2 solved this. : )

Hi sorry to bother you.
I don't understand where to change this and what to do. I don't find the solution following the previous post.
Thank you.

**Comment by nickvergessen** [comment]
See #19150

Or just update to the latest versions
